import type { Metadata } from "next";
import './global.css';

export const metadata : Metadata = {
  title: "Metalizze",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: '#111', color: '#fff', fontFamily: 'sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
