import type { Metadata } from "next";
import './global.css';
import { Poppins } from "next/font/google";

export const metadata : Metadata = {
  title: "Metalizze",
  description: "Generated by create next app",
};

const poppinsRegular = Poppins({ weight: ['400', '500', '700'], subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        style={{ backgroundColor: '#111', color: '#fff', fontFamily: poppinsRegular.style.fontFamily }}
      >
        {children}
      </body>
    </html>
  );
}
